spring.datasource.url=${RESERVA_DB_URL:jdbc:h2:mem:reservapatterns;DB_CLOSE_DELAY=-1}
spring.datasource.username=${reservalab:sa}
spring.datasource.password=${RESERVA_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.error.include-message=never
reserva.security.jwt-secret=${29507d58acdb9b42b831d23a0f34f7d1b629462f2f83bd3dab675024abef2aed}
reserva.bootstrap.username=${admin}
reserva.bootstrap.password=${senha1234}